# Generated by Django 5.1.6 on 2025-02-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компонента')),
                ('component_type', models.CharField(choices=[('cpu', 'Процессор'), ('cooling', 'Охлаждение'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('gpu', 'Видеокарта'), ('hdd', 'Жёсткий диск'), ('ssd', 'SSD диск'), ('psu', 'Блок питания'), ('case', 'Корпус'), ('wifi', 'Wi-Fi адаптер'), ('sound_card', 'Звуковая карта'), ('os', 'Операционная система'), ('mouse', 'Мышь'), ('keyboard', 'Клавиатура'), ('monitor', 'Монитор'), ('headset', 'Гарнитура')], max_length=20, verbose_name='Тип компонента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='PCConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ПК')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('cheap', 'Недорогие ПК'), ('gaming', 'Игровые ПК'), ('powerful', 'Мощные ПК'), ('amd', 'ПК на базе AMD')], max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'case'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='configurator.component', verbose_name='Корпус')),
                ('cooling', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'cooling'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coolings', to='configurator.component', verbose_name='Охлаждение')),
                ('cpu', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'cpu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpus', to='configurator.component', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'gpu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpus', to='configurator.component', verbose_name='Видеокарта')),
                ('hdd', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'hdd'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdds', to='configurator.component', verbose_name='Жёсткий диск')),
                ('headset', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'headset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headsets', to='configurator.component', verbose_name='Гарнитура')),
                ('keyboard', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'keyboard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboards', to='configurator.component', verbose_name='Клавиатура')),
                ('monitor', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'monitor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='configurator.component', verbose_name='Монитор')),
                ('motherboard', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'motherboard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboards', to='configurator.component', verbose_name='Материнская плата')),
                ('mouse', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'mouse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouses', to='configurator.component', verbose_name='Мышь')),
                ('os', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'os'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oss', to='configurator.component', verbose_name='Операционная система')),
                ('psu', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'psu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psus', to='configurator.component', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'ram'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rams', to='configurator.component', verbose_name='Оперативная память')),
                ('sound_card', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'sound_card'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound_cards', to='configurator.component', verbose_name='Звуковая карта')),
                ('ssd', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'ssd'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssds', to='configurator.component', verbose_name='SSD диск')),
                ('wifi', models.ForeignKey(blank=True, limit_choices_to={'component_type': 'wifi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifis', to='configurator.component', verbose_name='Wi-Fi адаптер')),
                ('configurator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='configurator.pcconfigurator')),
            ],
        ),
    ]
